version: 2
jobs:
  build-publish-trigger:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build tools and test them
          command: |
            set -e
            SCRIPT=run_build_image2.sh
            curl -O --fail https://raw.githubusercontent.com/cyber-dojo-languages/image_builder/master/${SCRIPT}
            chmod 700 ./${SCRIPT}
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            ./${SCRIPT}

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-languages-context
          filters:
            branches:
              only:
                  - master
