version: 2
jobs:
  build-publish-trigger:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build image, test it, push it dockerhub, notify dependents
          command: |
            set -e
            SCRIPT=build_test_push_notify.sh
            curl -O --fail ${CIRCLECI_SCRIPT_DIR}/${SCRIPT}
            chmod 700 ./${SCRIPT}
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            ./${SCRIPT}

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          filters:
            branches:
              only:
                  - master
